HEADER:
  label: "About me"

PRESENTATION:
  description: |
    I am a Data Scientist with over 4 years of experience building and deploying machine learning and deep learning solutions across finance, retail, and telecom sectors. My core strengths include natural language processing, time series forecasting, and large language models (LLMs). I’ve developed models that improved business KPIs by up to 30%, working with tools like TensorFlow, PyTorch, and Scikit-learn, and deploying them across AWS, GCP, and Azure environments.

    I specialize in scalable ML systems—designing robust data pipelines using Apache Spark, Kafka, and Airflow, and deploying models with FastAPI and Kubernetes. With a strong focus on MLOps, feature engineering, and model optimization, I bring together data science and engineering to deliver production-grade, responsible AI solutions that drive real business impact.

DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "Machine Learning & Model Development"
      icon: "config/assets/icons/mobile.svg"
      description: "Building and deploying scalable machine learning models for classification, forecasting, and anomaly detection using Scikit-learn, XGBoost, TensorFlow, and PyTorch. Specializing in NLP and LLM-based solutions with Hugging Face Transformers."
    - title: " MLOps & Cloud Deployment"
      icon: "config/assets/icons/code.svg"
      description: "Automating ML pipelines and production deployments using Docker, Kubernetes, and CI/CD workflows across cloud platforms including AWS SageMaker, GCP Vertex AI, and Azure ML Studio—ensuring reliability and scalability."
    - title: "Applied Data Science & Analytics"
      icon: "config/assets/icons/compass.svg"
      description: "Developing end-to-end data science solutions using statistical modeling, machine learning, and deep learning techniques. Leveraging tools like Scikit-learn, TensorFlow, and PyTorch to solve business problems in forecasting, classification, and customer analytics—translating complex data into clear, actionable insights."
    - title: "Model Monitoring & Responsible AI"
      icon: "config/assets/icons/laptop-code.svg"
      description: "Developing dashboards to monitor model drift, latency, and accuracy using Power BI and Prometheus. Ensuring fairness, explainability, and compliance with Responsible AI practices."

SKILLS:
  enabled: true
  label: "Soft Skills"
  items:
    - title: "Fast Learner"
      icon: "config/assets/icons/bolt.svg"
      description: "I have the ability to quickly acquire new knowledge and adapt to changing technological environments."
    - title: "Teamwork"
      icon: "config/assets/icons/user.svg"
      description: "I collaborate effectively in multidisciplinary projects and communicate clearly with team members."
    - title: "Problem Solving"
      icon: "config/assets/icons/gear.svg"
      description: "I am creative and efficient in identifying and solving technical problems."
    - title: "Effective Communication"
      icon: "config/assets/icons/comment.svg"
      description: "I have the skill to convey ideas clearly and concisely, both technically and non-technically."

TECHNOLOGIES:
  enabled: true
  label: "Tech Experience"
  items:
    - title: "Python"
      icon: "config/assets/icons/python.svg"
    - title: "TensorFlow"
      icon: "config/assets/icons/tensorflow.svg"
    - title: "PyTorch"
      icon: "config/assets/icons/pytorch.svg"
    - title: "Scikit-learn"
      icon: "config/assets/icons/Scikit_learn.svg"
    - title: "Hugging Face"
      icon: "config/assets/icons/hugging-face.svg"
    - title: "Pandas"
      icon: "config/assets/icons/pandas.svg"
    - title: "NumPy"
      icon: "config/assets/icons/numpy.svg"
    - title: "Jupyter"
      icon: "config/assets/icons/jupyter.svg"
    - title: "MySQL"
      icon: "config/assets/icons/mysql.svg"
    - title: "Docker"
      icon: "config/assets/icons/docker.svg"
    - title: "Kubernetes"
      icon: "config/assets/icons/Kubernetes.svg"
    - title: "Power BI"
      icon: "config/assets/icons/p.svg"
    - title: "Snowflake"
      icon: "config/assets/icons/snowflake.svg"
