HEADER:
  label: "Contact"

LOCATION:
  embed: "<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d20944.151752966656!2d-121.89854018285368!3d37.33310215841022!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fcc95b3fe3579%3A0x9cbfbc6cfb3cdda5!2sSan%20Jose%2C%20CA%2095112!5e1!3m2!1sen!2sus!4v1745352430084!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>"

FORM:
  label: "Contact Form"
  fields:
    - name: "Full name"
    - email: "Email address"
    - message: "Your message"
    - submit: "Send message"
