# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Data Scientist"
  name: "Kiran Kumar Katamneni"
  username: "KiranKatamneni" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "kirankatamaneni25@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+1 (408) 641-0839"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "May 25, 2001"
    icon: "calendar-outline"
  - label: "Location"
    value: "San Jose, California, USA"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/in/kirankatamneni05/"
  - icon: "logo-github"
    url: "https://github.com/KiranKatamneni"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
