HEADER:
  label: "Portfolio"

PROJECTS:
  - title: "Anime_Recommendation_MLOPS"
    category: "Data Science"
    image: "https://i.imgur.com/ANDVQ4o.png"
    url: "https://github.com/KiranKatamneni/Anime_Recommendation_MLOps"

  - title: "Generative AI"
    category: "Generative AI"
    image: "https://imgur.com/2nNXhDN.png"
    url: "https://github.com/KiranKatamneni/Gen-AI"

  - title: "Customer-Churn-Prediction"
    category: "Data Science"
    image: "https://imgur.com/7110Lj1.png"
    url: "https://github.com/KiranKatamneni/Customer-Churn-Prediction"

  - title: "Sales-Dasboard-Power-BI"
    category: "PowerBI Dashboard"
    image: "https://imgur.com/t5T5Ixa.png"
    url: "https://github.com/KiranKatamneni/Sales-Dasboard-Power-BI"

  - title: "Financial-Market-Forecasting"
    category: "Data Science"
    image: "https://imgur.com/kyHrBGk.png"
    url: "https://github.com/KiranKatamneni/Financial-Market-Forecasting"

  - title: "AI Story Teller"
    category: "Generative AI"
    image: "config/assets/projects/project-1.jpg"
    url: "https://github.com/KiranKatamneni/Capstone"

  - title: "Restaurant Data Analysis"
    category: "Data Analysis"
    image: "config/assets/projects/project-2.png"
    url: "https://github.com/KiranKatamneni/Zomato-Restaurant-Data-Analysis-using-Streamlit"

  - title: "Netflix Dashboard"
    category: "Data Visualization"
    image: "config/assets/projects/project-3.jpg"
    url: "https://public.tableau.com/app/profile/katamneni.kiran.kumar/viz/Netflix_16844275441000/Dashboard1"

  - title: "Walmart Retail Data Analysis"
    category: "Data Visualization"
    image: "config/assets/projects/project-4.png"
    url: "https://public.tableau.com/app/profile/katamneni.kiran.kumar/viz/Walmart_16444143836870/Dashboard1"
