HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2024"
      institution: "University of Texas at Arlington"
      description: "Master of Science in Data Science. Focused on machine learning, natural language processing, time series forecasting, and cloud deployment. Applied real-world AI solutions through academic and project-based learning."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Jan 2024 — Present"
      position: "Data Scientist I – Accenture"
      description: >
        Developed a time series forecasting system improving price predictions by 20%. 
        Built real-time data pipelines with Kafka, reducing lag to 6 seconds. 
        Deployed risk and fraud detection models using Gradient Boosting and LLMs, improving accuracy and reducing review times.
        Delivered a real-time Power BI dashboard for model monitoring with 99.5% uptime.
    - period: "Aug 2021 — Dec 2022"
      position: "Data Scientist – LTIMindtree"
      description: >
        Designed LSTM models to reduce retail stockouts by 25%. 
        Built Airflow-BigQuery pipelines for real-time analytics, cut data processing time by 78%. 
        Tuned Transformer-based pricing models that boosted revenue by 12%.
    - period: "May 2020 — Jul 2021"
      position: "Junior Data Scientist – LTIMindtree"
      description: >
        Built CNN-based product classification models for e-commerce, reducing manual effort by 35%. 
        Created churn prediction models and improved retention strategies, leading to a 20% drop in churn. 
        Integrated MLOps workflows using Kubernetes and OpenCV for image-based analytics.

SKILLS:
  enabled: true
  label: "My Skills"
  items:
    - skill: "Programming: Python, SQL, R, PySpark"
    - skill: "Machine Learning & Deep Learning: Scikit-learn, XGBoost, TensorFlow, PyTorch, Hugging Face"
    - skill: "Natural Language Processing: Transformers (BERT, GPT), SpaCy, NLTK"
    - skill: "Cloud Platforms: AWS (SageMaker, S3, Lambda), GCP (Vertex AI, BigQuery), Azure (ML Studio, Data Factory)"
    - skill: "Data Engineering & Orchestration: Apache Spark, Kafka, Airflow, DBT"
    - skill: "Model Deployment & MLOps: FastAPI, Docker, Kubernetes, CI/CD (GitHub Actions, Jenkins)"
    - skill: "Visualization Tools: Power BI, Tableau, Matplotlib, Seaborn"
    - skill: "Monitoring & Data Quality: Prometheus, Grafana, Great Expectations"
    - skill: "Data Warehousing: Snowflake, BigQuery, Redshift"
    - skill: "Version Control & Collaboration: Git, GitHub"
