HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2024"
      institution: "University of Texas at Arlington"
      description: "Master of Science in Data Science. Focused on machine learning, natural language processing, time series forecasting, and cloud deployment. Applied real-world AI solutions through academic and project-based learning."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Jan 2024 — Present"
      position: "Data Scientist – Goldman Sachs Group"
      description: >
        Developed end-to-end ML pipelines using Python and XGBoost, improving prediction accuracy by 10%. 
        Built a Generative AI-powered financial chatbot with LLaMA 2.0, GPT-3.5, and RAG for real-time insights. 
        Created Power BI dashboards integrated with AWS Redshift for KPI tracking. 
        Delivered scalable AI solutions across the full pipeline, including deep learning, GAN-based data augmentation, and cloud deployment.
    - period: "Aug 2021 — Dec 2022"
      position: "Data Scientist – LTIMindtree"
      description: >
        Led the development of AI-driven tools for data analysis and validation using Python and SQL, improving data quality and preprocessing efficiency by 90% in healthcare projects. 
        Built predictive models with Scikit-learn, Spark, and advanced ML algorithms, boosting accuracy by 18%. 
        Architected scalable AI solutions using Python, Streamlit, and Tableau, reducing analysis time by 80% and enhancing governance. 
        Deployed ML and deep learning models on GCP for real-time Generative AI integration, cutting deployment time by 25%. 
        Applied GANs and transformer models for synthetic data generation and anomaly detection, improving model generalization, reliability, and training on sparse datasets.
    - period: "May 2020 — Jul 2021"
      position: "Junior Data Scientist – LTIMindtree"
      description: >
        Applied a wide range of machine learning algorithms—including linear regression, random forest, SVMs, clustering, CNNs, RNNs, and transformers—to solve complex AI and Generative AI challenges across diverse datasets. 
        Delivered end-to-end ML models with Scikit-learn, achieving 92% accuracy in customer churn prediction. 
        Enhanced decision-making through Power BI dashboards and Python-SQL pipelines for real-time KPI tracking. 
        Used NLP tools like NLTK to reduce text data dimensionality, and engineered synthetic data with GANs to address class imbalance. 
        Optimized SQL Server for high-throughput ingestion, and collaborated with cross-functional teams to support AI-driven solutions for Fortune 500 clients.

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  label: "My Skills"
  items:
     - skill: "Language and Tools: Python, R, SQL, Spark, Vertex AI, Generative AI"
     - skill: "IDEs: Visual Studio Code, Jupyter Notebook, PyCharm"
     - skill: "ML Algorithms: Linear Regression, Logistic Regression, Decision Trees, Random Forests, XGBoost, K-Means, SVM"
     - skill: "Deep Learning: ANN, CNN, LSTMs, Transformers (BERT, GPT), Hugging Face"
     - skill: "Packages: NumPy, Pandas, Scikit-learn, TensorFlow, PyTorch, Keras, OpenCV"
     - skill: "Cloud Technology: AWS (SageMaker, Lambda, S3), GCP (BigQuery, Vertex AI)"
     - skill: "Big Data & Data Engineering: Apache Spark, Databricks, Airflow"
     - skill: "MLOps & Model Deployment: Docker, Kubernetes, CI/CD Pipelines, FastAPI"
     - skill: "Visualization Tools: Tableau, Power BI, Matplotlib, Seaborn"
     - skill: "Database: SQL Server, MySQL, PostgreSQL, Snowflake"

