HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2024"
      institution: "University of Texas at Arlington"
      description: "Master of Science in Data Science. Focused on machine learning, natural language processing, time series forecasting, and cloud deployment. Applied real-world AI solutions through academic and project-based learning."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Jan 2024 — Present"
      position: "Data Scientist I – Accenture"
      description: >
        Developed a time series forecasting system improving price predictions by 20%. 
        Built real-time data pipelines with Kafka, reducing lag to 6 seconds. 
        Deployed risk and fraud detection models using Gradient Boosting and LLMs, improving accuracy and reducing review times.
        Delivered a real-time Power BI dashboard for model monitoring with 99.5% uptime.
    - period: "Aug 2021 — Dec 2022"
      position: "Data Scientist – LTIMindtree"
      description: >
        Designed LSTM models to reduce retail stockouts by 25%. 
        Built Airflow-BigQuery pipelines for real-time analytics, cut data processing time by 78%. 
        Tuned Transformer-based pricing models that boosted revenue by 12%.
    - period: "May 2020 — Jul 2021"
      position: "Junior Data Scientist – LTIMindtree"
      description: >
        Built CNN-based product classification models for e-commerce, reducing manual effort by 35%. 
        Created churn prediction models and improved retention strategies, leading to a 20% drop in churn. 
        Integrated MLOps workflows using Kubernetes and OpenCV for image-based analytics.

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  label: "My Skills"
  items:
     - skill: "Language and Tools: Python, R, SQL, Spark, Vertex AI, Generative AI"
     - skill: "IDEs: Visual Studio Code, Jupyter Notebook, PyCharm"
     - skill: "ML Algorithms: Linear Regression, Logistic Regression, Decision Trees, Random Forests, XGBoost, K-Means, SVM"
     - skill: "Deep Learning: ANN, CNN, LSTMs, Transformers (BERT, GPT), Hugging Face"
     - skill:"Packages: NumPy, Pandas, Scikit-learn, TensorFlow, PyTorch, Keras, OpenCV"
     - skill: "Cloud Technology: AWS (SageMaker, Lambda, S3), GCP (BigQuery, Vertex AI)"
     - skill: "Big Data & Data Engineering: Apache Spark, Databricks, Airflow"
     - skill: "MLOps & Model Deployment: Docker, Kubernetes, CI/CD Pipelines, FastAPI"
     - skill: "Visualization Tools: Tableau, Power BI, Matplotlib, Seaborn"
     - skill: "Database: SQL Server, MySQL, PostgreSQL, Snowflake"

