HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2024"
      institution: "University of Texas at Arlington"
      description: "Master of Science in Data Science. Focused on machine learning, natural language processing, time series forecasting, and cloud deployment. Applied real-world AI solutions through academic and project-based learning."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Jan 2024 — Present"
      position: "Data Scientist – Goldman Sachs Group"
      description: >
        Developed end-to-end ML pipelines using Python and XGBoost, improving prediction accuracy by 10%. 
        Built a Generative AI-powered financial chatbot with LLaMA 2.0, GPT-3.5, and RAG for real-time insights. 
        Created Power BI dashboards integrated with AWS Redshift for KPI tracking. 
        Delivered scalable AI solutions across the full pipeline, including deep learning, GAN-based data augmentation, and cloud deployment.
    - period: "Aug 2021 — Dec 2022"
      position: "Data Scientist – LTIMindtree"
      description: >
       Built scalable AI tools using Python, SQL, and GCP, improving data quality by 90% and cutting deployment time by 25%. 
       Developed ML models with Spark and GANs for anomaly detection, synthetic data generation, and automation, enhancing model accuracy and reliability.
    - period: "May 2020 — Jul 2021"
      position: "Junior Data Scientist – LTIMindtree"
      description: >
        Deployed ML models using Scikit-learn and transformers, achieving 92% churn prediction accuracy. 
        Enhanced insights with Power BI dashboards and Python-SQL pipelines. 
        Applied GANs, NLP, and deep learning (CNNs/RNNs) to tackle class imbalance, improve pattern recognition, and support enterprise AI solutions.

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"
      
SKILLS:
  enabled: true
  label: "My Skills"
  items:
     - skill: "Language and Tools: Python, R, SQL, Spark, Vertex AI, Generative AI"
     - skill: "IDEs: Visual Studio Code, Jupyter Notebook, PyCharm"
     - skill: "ML Algorithms: Linear Regression, Logistic Regression, Decision Trees, Random Forests, XGBoost, SVM, K-Means, Naive Bayes, PCA"
     - skill: "Deep Learning: CNN, RNN, LSTM, Transformers (BERT, GPT, T5, LLAMA), Hugging Face, Stable Diffusion, Generative AI (GenAI), OpenCV"
     - skill: "Packages: NumPy, Pandas, Scikit-learn, TensorFlow, PyTorch, Keras, Seaborn, Matplotlib, Plotly, SciPy, MLflow, NLTK, spaCy"
     - skill: "Cloud Technology: AWS (EC2, S3, Lambda, SageMaker, EMR, DynamoDB), GCP (BigQuery, Vertex AI)"
     - skill: "Big Data & Data Engineering: Apache Spark, Databricks, Snowflake, Airflow"
     - skill: "MLOps & Model Deployment: Docker, Kubernetes, CI/CD Pipelines, RESTful APIs"
     - skill: "Visualization Tools: Tableau, Power BI, Matplotlib, Seaborn"
     - skill: "Database: PostgreSQL, MySQL, SQL Server, MongoDB, Cassandra, SPSS"

